from __future__ import annotations

import argparse
import copy
import difflib
import importlib
import inspect
import json
import pathlib
import pkgutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from types import ModuleType
from typing import Any

import httpx2

SPEC_URL = "https://api.discolike.com/v1/openapi.json"
REQUEST_TIMEOUT_SECONDS = 30.0
REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "packages" / "discolike" / "src" / "discolike" / "_generated" / "requests.py"
RUFF_CONFIG = REPO_ROOT / "pyproject.toml"
BASE_CLASS = "discolike._models.DiscolikeRequest"
FILE_HEADER = "# Generated by scripts/gen_requests.py from the platform OpenAPI spec. Do not edit by hand."
JSON_MEDIA_TYPE = "application/json"
QUERY_LOCATION = "query"
NULL_SCHEMA = {"type": "null"}
ITEM_KEYS_KEPT = frozenset({"type", "enum", "format", "$ref"})
CLIENT_LEVEL_RESOURCES = frozenset({"DiscoveryResource", "EnrichResource", "ValidateResource"})
ASYNC_CLASS_PREFIX = "Async"
RESOURCE_SUFFIX = "Resource"
PARAMS_SUFFIX = "Params"
CODEGEN_ARGS = [
    "--input-file-type",
    "openapi",
    "--output-model-type",
    "pydantic_v2.BaseModel",
    "--base-class",
    BASE_CLASS,
    "--use-annotated",
    "--field-constraints",
    "--use-standard-collections",
    "--use-union-operator",
    "--collapse-root-models",
    "--enum-field-as-literal",
    "all",
    "--target-python-version",
    "3.10",
    "--use-double-quotes",
    "--disable-timestamp",
    "--formatters",
    "builtin",
    "--custom-file-header",
    FILE_HEADER,
]


@dataclass(frozen=True)
class Route:
    class_name: str
    method_name: str
    http_method: str
    path: str


def _resource_modules() -> list[ModuleType]:
    import discolike.resources

    return [
        importlib.import_module(info.name)
        for info in pkgutil.walk_packages(discolike.resources.__path__, prefix=f"{discolike.resources.__name__}.")
    ]


def collect_routes() -> list[Route]:
    from discolike.resources._base import get_discolike_route

    routes: dict[tuple[str, str], Route] = {}
    for module in _resource_modules():
        for class_name, cls in inspect.getmembers(module, inspect.isclass):
            if cls.__module__ != module.__name__ or class_name.startswith(ASYNC_CLASS_PREFIX):
                continue
            for method_name, member in vars(cls).items():
                if not inspect.isfunction(member):
                    continue
                route = get_discolike_route(member)
                if route is None:
                    continue
                http_method, path, openapi = route
                if not openapi:
                    continue
                routes.setdefault((http_method, path), Route(class_name, method_name, http_method, path))
    return list(routes.values())


def params_model_name(*, class_name: str, method_name: str) -> str:
    prefix = "" if class_name in CLIENT_LEVEL_RESOURCES else class_name.removesuffix(RESOURCE_SUFFIX)
    return prefix + "".join(part.capitalize() for part in method_name.split("_")) + PARAMS_SUFFIX


def _synthesize_params_schema(operation: dict[str, Any]) -> dict[str, Any] | None:
    parameters = [
        parameter
        for parameter in operation.get("parameters", [])
        if parameter["in"] == QUERY_LOCATION and not parameter.get("deprecated", False)
    ]
    if not parameters:
        return None
    schema: dict[str, Any] = {
        "type": "object",
        "properties": {parameter["name"]: parameter["schema"] for parameter in parameters},
    }
    required = [parameter["name"] for parameter in parameters if parameter.get("required", False)]
    if required:
        schema["required"] = required
    return schema


def _body_ref_name(operation: dict[str, Any]) -> str | None:
    schema = operation.get("requestBody", {}).get("content", {}).get(JSON_MEDIA_TYPE, {}).get("schema", {})
    ref = schema.get("$ref")
    return None if ref is None else ref.rsplit("/", 1)[1]


def request_schemas(*, spec: dict[str, Any], routes: list[Route]) -> dict[str, dict[str, Any]]:
    schemas = spec["components"]["schemas"]
    requested: dict[str, dict[str, Any]] = {}
    for route in routes:
        operation = spec["paths"].get(route.path, {}).get(route.http_method.lower())
        if operation is None:
            raise SystemExit(f"{route.http_method} {route.path} is not in the spec; run scripts/check_contract.py")
        body_name = _body_ref_name(operation)
        if body_name is not None:
            requested[body_name] = copy.deepcopy(schemas[body_name])
            continue
        synthesized = _synthesize_params_schema(operation)
        if synthesized is not None:
            requested[params_model_name(class_name=route.class_name, method_name=route.method_name)] = synthesized
    return requested


def _collect_refs(node: Any, refs: set[str]) -> None:  # noqa: ANN401 -- walks arbitrary JSON
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str):
            refs.add(ref.rsplit("/", 1)[1])
        for value in node.values():
            _collect_refs(value, refs)
    elif isinstance(node, list):
        for item in node:
            _collect_refs(item, refs)


def prune(*, spec: dict[str, Any], requested: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
    schemas = spec["components"]["schemas"]
    kept = dict(requested)
    pending: set[str] = set()
    _collect_refs(kept, pending)
    while pending:
        # min() rather than pop(): set order varies with PYTHONHASHSEED, which would reorder
        # the generated classes between runs and make --check report phantom drift.
        name = min(pending)
        pending.remove(name)
        if name in kept:
            continue
        kept[name] = copy.deepcopy(schemas[name])
        _collect_refs(kept[name], pending)
    return kept


def _normalize_property(schema: dict[str, Any], *, required: bool) -> dict[str, Any]:
    variants = schema.get("anyOf")
    if not required and variants is not None and len(variants) == 2 and NULL_SCHEMA in variants:
        inner = next(variant for variant in variants if variant != NULL_SCHEMA)
        outer = {key: value for key, value in schema.items() if key != "anyOf"}
        schema = {**inner, **outer, "nullable": True}
    items = schema.get("items")
    if isinstance(items, dict):
        schema = {**schema, "items": {key: value for key, value in items.items() if key in ITEM_KEYS_KEPT}}
    return schema


def normalize_schema(schema: dict[str, Any]) -> dict[str, Any]:
    required = set(schema.get("required", []))
    properties = {
        name: _normalize_property(prop, required=name in required)
        for name, prop in schema.get("properties", {}).items()
        if not prop.get("deprecated", False)
    }
    return {key: value for key, value in schema.items() if key != "additionalProperties"} | {"properties": properties}


def build_codegen_spec(*, spec: dict[str, Any], routes: list[Route]) -> dict[str, Any]:
    kept = prune(spec=spec, requested=request_schemas(spec=spec, routes=routes))
    return {
        "openapi": "3.1.0",
        "info": {"title": "discolike request models", "version": "0"},
        "paths": {},
        "components": {"schemas": {name: normalize_schema(schema) for name, schema in kept.items()}},
    }


def generate(*, spec: dict[str, Any], output: pathlib.Path) -> None:
    codegen_spec = build_codegen_spec(spec=spec, routes=collect_routes())
    with tempfile.TemporaryDirectory() as tmp:
        spec_path = pathlib.Path(tmp) / "requests-spec.json"
        spec_path.write_text(json.dumps(codegen_spec))
        subprocess.run(  # noqa: S603 -- fixed argv, no shell
            [
                sys.executable,
                "-m",
                "datamodel_code_generator",
                "--input",
                str(spec_path),
                "--output",
                str(output),
                *CODEGEN_ARGS,
            ],
            check=True,
        )
    ruff = [sys.executable, "-m", "ruff"]
    subprocess.run(  # noqa: S603
        [*ruff, "check", "--fix", "--quiet", "--no-show-fixes", "--config", str(RUFF_CONFIG), str(output)], check=True
    )
    subprocess.run([*ruff, "format", "--quiet", "--config", str(RUFF_CONFIG), str(output)], check=True)  # noqa: S603


def compare(*, committed: str, fresh: str) -> int:
    relative = OUTPUT_PATH.relative_to(REPO_ROOT)
    if committed == fresh:
        print(f"{relative} is up to date")
        return 0
    sys.stdout.writelines(
        difflib.unified_diff(
            committed.splitlines(keepends=True),
            fresh.splitlines(keepends=True),
            fromfile=f"{relative} (committed)",
            tofile=f"{relative} (generated)",
        )
    )
    print(f"{relative} is stale; run: uv run python scripts/gen_requests.py")
    return 1


def check(*, spec: dict[str, Any]) -> int:
    if not OUTPUT_PATH.exists():
        relative = OUTPUT_PATH.relative_to(REPO_ROOT)
        print(f"{relative} is stale; run: uv run python scripts/gen_requests.py")
        return 1
    with tempfile.TemporaryDirectory() as tmp:
        candidate = pathlib.Path(tmp) / OUTPUT_PATH.name
        generate(spec=spec, output=candidate)
        fresh = candidate.read_text()
    return compare(committed=OUTPUT_PATH.read_text(), fresh=fresh)


def load_spec(*, spec_path: str | None, spec_url: str) -> dict[str, Any]:
    if spec_path is not None:
        return json.loads(pathlib.Path(spec_path).read_text())
    response = httpx2.get(spec_url, timeout=REQUEST_TIMEOUT_SECONDS)
    response.raise_for_status()
    return response.json()


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate SDK request models from the platform OpenAPI spec.")
    parser.add_argument("--spec", default=None, help="Path to a local OpenAPI spec JSON file (offline mode).")
    parser.add_argument("--spec-url", default=SPEC_URL, help="OpenAPI spec URL (defaults to the production spec).")
    parser.add_argument("--check", action="store_true", help="Regenerate to a temp file and fail if it differs.")
    args = parser.parse_args()
    spec = load_spec(spec_path=args.spec, spec_url=args.spec_url)
    if args.check:
        return check(spec=spec)
    generate(spec=spec, output=OUTPUT_PATH)
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
